# Generated by Django 4.2.17 on 2025-01-07 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demoprofile',
            name='demo_field',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Demo Field'),
        ),
        migrations.AlterField(
            model_name='demoprofile',
            name='demo_secret',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Demo Secret'),
        ),
    ]
