# Generated by Django 5.2.13 on 2026-04-28 23:41

import django.db.models.deletion
import tom_regions.healpix_django.fields
import tom_regions.healpix_django.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique human-readable name. Aliases live in RegionName.', max_length=200, unique=True)),
                ('type', models.CharField(choices=[('POLYGON', 'Polygon'), ('CIRCLE', 'Circle'), ('FITS_MOC', 'MOC FITS'), ('SKYMAP', 'Skymap')], default='POLYGON', help_text='How this region was constructed; informational, not enforced.', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('area_sr', models.FloatField(blank=True, help_text='Total solid angle in steradians.', null=True)),
                ('centroid_ra', models.FloatField(blank=True, null=True)),
                ('centroid_dec', models.FloatField(blank=True, null=True)),
                ('n_tiles', models.PositiveIntegerField(default=0)),
                ('max_depth', models.PositiveSmallIntegerField(blank=True, help_text='Deepest HEALPix order present in the tile set.', null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('regions', models.ManyToManyField(blank=True, related_name='region_lists', to='regions.region')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RegionName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='regions.region')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RegionTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hpx', tom_regions.healpix_django.fields.HealpixTileField()),
                ('probdensity', models.FloatField(blank=True, help_text='Probability density in inverse steradians; non-null for skymap tiles.', null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiles', to='regions.region')),
            ],
            options={
                'abstract': False,
                'indexes': [tom_regions.healpix_django.indexes.HealpixSpGistIndex(fields=['hpx'], name='regions_reg_hpx_b4c7a1_spgist')],
            },
        ),
    ]
