# Generated by Django 5.2.13 on 2026-04-29 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='type',
            field=models.CharField(choices=[('ALADIN', 'Aladin'), ('FITS_MOC', 'MOC FITS'), ('OTHER', 'Other')], default='OTHER', help_text='How this region was constructed; informational, not enforced.', max_length=20),
        ),
    ]
