# Generated by Django 5.2.13 on 2026-06-03 00:36

import tom_regions.healpix_django.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_alter_region_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetHealpix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.BigIntegerField(help_text='Primary key of the Target this point caches (a plain id, not a FK, by design).', unique=True)),
                ('hpx', tom_regions.healpix_django.fields.HealpixPointField(db_index=True, help_text="The target's position as a deepest-level NESTED HEALPix pixel index.")),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'target HEALPix point',
                'verbose_name_plural': 'target HEALPix points',
            },
        ),
    ]
